local testkit = require("tests.testkit")
local stateMod = dofile("src/SCRIPTS/TOOLS/BFDash/state.lua")

testkit.describe("state", function()
    testkit.it("loads values and starts clean", function()
        local s = stateMod.new()
        s:load("pids", { masterMultiplier = 100 })
        testkit.assertEquals(s:isDirty("pids"), false, "clean after load")
        testkit.assertEquals(s:get("pids").masterMultiplier, 100, "value readable")
    end)

    testkit.it("marks a key dirty after setField changes a value", function()
        local s = stateMod.new()
        s:load("pids", { masterMultiplier = 100 })
        s:setField("pids", "masterMultiplier", 120)
        testkit.assertEquals(s:isDirty("pids"), true, "dirty after edit")
        testkit.assertEquals(s:get("pids").masterMultiplier, 120, "staged value updated")
    end)

    testkit.it("does not mark dirty if setField sets the same value", function()
        local s = stateMod.new()
        s:load("pids", { masterMultiplier = 100 })
        s:setField("pids", "masterMultiplier", 100)
        testkit.assertEquals(s:isDirty("pids"), false, "unchanged value stays clean")
    end)

    testkit.it("reload discards staged edits back to the clean baseline", function()
        local s = stateMod.new()
        s:load("pids", { masterMultiplier = 100 })
        s:setField("pids", "masterMultiplier", 120)
        s:reload("pids")
        testkit.assertEquals(s:get("pids").masterMultiplier, 100, "reverted")
        testkit.assertEquals(s:isDirty("pids"), false, "clean after reload")
    end)

    testkit.it("markClean commits the staged values as the new baseline", function()
        local s = stateMod.new()
        s:load("pids", { masterMultiplier = 100 })
        s:setField("pids", "masterMultiplier", 120)
        s:markClean("pids")
        testkit.assertEquals(s:isDirty("pids"), false, "clean after markClean")
        s:reload("pids")
        testkit.assertEquals(s:get("pids").masterMultiplier, 120, "new baseline is 120, not 100")
    end)

    testkit.it("isAnyDirty reflects dirtiness across multiple keys", function()
        local s = stateMod.new()
        s:load("pids", { masterMultiplier = 100 })
        s:load("rates", { rcRateRoll = 7 })
        testkit.assertEquals(s:isAnyDirty(), false, "nothing dirty yet")
        s:setField("rates", "rcRateRoll", 8)
        testkit.assertEquals(s:isAnyDirty(), true, "dirty via rates key")
    end)

    testkit.it("clear removes both clean and staged values for a key", function()
        local s = stateMod.new()
        s:load("pids", { masterMultiplier = 100 })
        s:clear("pids")
        testkit.assertEquals(s:get("pids"), nil, "staged cleared")
        testkit.assertEquals(s:isDirty("pids"), false, "cleared key is not dirty")
        testkit.assertEquals(s:isAnyDirty(), false, "cleared key does not affect isAnyDirty")
    end)
end)
