local testkit = require("tests.testkit")
local mspBuffer = dofile("src/SCRIPTS/TOOLS/BFDash/transport/mspBuffer.lua")

testkit.describe("mspBuffer", function()
    testkit.it("reads a 1-byte field", function()
        local buf = string.char(10, 20, 30)
        testkit.assertEquals(mspBuffer.readField(buf, { offset = 2, size = 1 }), 20, "field value")
    end)

    testkit.it("reads a 2-byte little-endian field", function()
        local buf = string.char(0, 0x34, 0x12, 0)
        testkit.assertEquals(mspBuffer.readField(buf, { offset = 2, size = 2 }), 0x1234, "field value")
    end)

    testkit.it("writes a 1-byte field and preserves buffer length and neighbors", function()
        local buf = string.char(1, 2, 3)
        local result = mspBuffer.writeField(buf, { offset = 2, size = 1 }, 99)
        testkit.assertEquals(#result, 3, "length preserved")
        testkit.assertEquals(mspBuffer.readField(result, { offset = 1, size = 1 }), 1, "byte 1 untouched")
        testkit.assertEquals(mspBuffer.readField(result, { offset = 2, size = 1 }), 99, "byte 2 patched")
        testkit.assertEquals(mspBuffer.readField(result, { offset = 3, size = 1 }), 3, "byte 3 untouched")
    end)

    testkit.it("writes a 2-byte field and preserves buffer length and neighbors", function()
        local buf = string.char(255, 0, 0, 255)
        local result = mspBuffer.writeField(buf, { offset = 2, size = 2 }, 0x1234)
        testkit.assertEquals(#result, 4, "length preserved")
        testkit.assertEquals(mspBuffer.readField(result, { offset = 1, size = 1 }), 255, "byte 1 untouched")
        testkit.assertEquals(mspBuffer.readField(result, { offset = 2, size = 2 }), 0x1234, "bytes 2-3 patched")
        testkit.assertEquals(mspBuffer.readField(result, { offset = 4, size = 1 }), 255, "byte 4 untouched")
    end)
end)
